export const MAIN_ROUTE = '/'
export const MAP_ROUTE = '/map'
export const ABOUT_ROUTE = '/map'
export const TABLE_ROUTE = '/telemetry'
export const REPORT_ROUTE = '/report'
export const REPORT_ROUTE_FULL = '/report/:id'
export const TRACTOR_REPORTS_ROUTE = '/tractors'
export const ANY_ROUTE = '*'